"""add soft delete to regions

Revision ID: 246b55ebf6ee
Revises: b43890c4139f
Create Date: 2026-04-26 17:29:36.357659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '246b55ebf6ee'
down_revision: Union[str, Sequence[str], None] = 'b43890c4139f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('regions', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.execute("UPDATE regions SET is_deleted = false WHERE is_deleted IS NULL")
    op.alter_column('regions', 'is_deleted', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regions', 'is_deleted')
    # ### end Alembic commands ###
