"""initial and add et0 solar radiation

Revision ID: b43890c4139f
Revises: 
Create Date: 2026-04-23 02:56:34.726635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b43890c4139f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_data', sa.Column('et0_evapotranspiration', sa.Float(), nullable=True))
    op.add_column('weather_data', sa.Column('solar_radiation', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_data', 'solar_radiation')
    op.drop_column('weather_data', 'et0_evapotranspiration')
    # ### end Alembic commands ###
